name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install pytest
        run: pip install pytest

      - name: Set PYTHONPATH   # ⬅️ TAMBAHAN PENTING
        run: echo "PYTHONPATH=." >> $GITHUB_ENV

      - name: Run test
        run: pytest